[package]
name = "skynet-robots"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = { version = "0.39.2", features = ["lazy", "regex", "strings", "ndarray"] }
